name: CD

on:
  push:
    branches:
      - main

jobs:
  clourflare_worker:
    name: Deploy to Cloudflare workers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  docker:
    name: Publish to Docker
    runs-on: ubuntu-latest
    environment:
      name: docker
      url: https://hub.docker.com/r/goquibble/avatars
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/avatars:latest
